# [과제] 보스턴 집값 데이터를 활용하여 다음 두가지 과제를 수행하고 각각의 score를 확인하세요(폴드 수: 5, shuffle=False)

#### 1. KFold 객체를 활용하되 인덱스 집합을 리턴받아 학습을 수행하여 r2값을 구하시오.(소숫점 이하 3자리)

In [14]:
import numpy as np
import pandas as pd

In [15]:
# 데이터 수집
from sklearn import datasets
boston = datasets.fetch_openml('boston')
boston

/Users/kimminsoo/opt/anaconda3/lib/python3.9/site-packages/sklearn/datasets/_openml.py:292: UserWarning: Multiple active versions of the dataset matching the name boston exist. Versions may be fundamentally different, returning version 1.
  warn(

{'data':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT
 0       15.3  396.90   4.98
 1       17.8  396.90   9.14
 2       17.8  392.83   4.03
 3       18.7  394.63   2.94
 4       18.7  396.90   5.33
 ..       ...     ...    ...
 501     21.0  391.99   9.67
 502     21.0  396.90   9.08
 503     21.0  396.90   5.64
 504     21.0  393.45   6.48
 505     21.0  396.90   7.88

 [506 rows x 13 columns],
 'target': 0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ...
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
 'frame':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT  MEDV
 0       15.3  396.90   4.98  24.0
 1       17.8  396.90   9.14  21.6
 2       17.8  392.83   4.03  34.7
 3       18.7  394.63   2.94  33.4
 4       18.7  396.90   5.33  36.2
 ..       ...     ...    ...   ...
 501     21.0  391.99   9.67  22.4
 502     21.0  396.90   9.08  20.6
 503     21.0  396.90   5.64  23.9
 504     21.0  393.45   6.48  22.0
 505     21.0  396.90   7.88  11.9

 [506 rows x 14 columns],
 'categories': None,
 'feature_names': ['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 'target_names': ['MEDV'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.",
 'details': {'id': '531',
  'name': 'boston',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"],
  'collection_date': '1978',
  'upload_date': '2014-09-29T00:08:07',
  'language': 'English',
  'licence': 'Public',
  'url': 'https://api.openml.org/data/v1/download/52643/boston.arff',
  'parquet_url': 'http://openml1.win.tue.nl/dataset531/dataset_531.pq',
  'file_id': '52643',
  'default_target_attribute': 'MEDV',
  'tag': ['OpenML-Reg19', 'study_130'],
  'visibility': 'public',
  'minio_url': 'http://openml1.win.tue.nl/dataset531/dataset_531.pq',
  'status': 'active',
  'processing_date': '2020-11-20 20:16:37',
  'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'},
 'url': 'https://www.openml.org/d/531'}

In [16]:
# 데이터 이해
dir(boston), boston.keys()

(['DESCR',
  'categories',
  'data',
  'details',
  'feature_names',
  'frame',
  'target',
  'target_names',
  'url'],
 dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url']))

In [17]:
print(boston.DESCR)

**Author**:
**Source**: Unknown - Date unknown
**Please cite**:

The Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic
prices and the demand for clean air', J. Environ. Economics & Management,
vol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics
...', Wiley, 1980.   N.B. Various transformations are used in the table on
pages 244-261 of the latter.
Variables in order:
CRIM     per capita crime rate by town
ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS    proportion of non-retail business acres per town
CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
NOX      nitric oxides concentration (parts per 10 million)
RM       average number of rooms per dwelling
AGE      proportion of owner-occupied units built prior to 1940
DIS      weighted distances to five Boston employment centres
RAD      index of accessibility to radial highways
TAX      full-value property-tax rate per $10,000
PTRATIO  pupil-teacher ratio by town
B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT    % lower status of the population
MEDV     Median value of owner-occupied homes in $1000's


Information about the dataset
CLASSTYPE: numeric
CLASSINDEX: last

Downloaded from openml.org.

In [18]:
boston.feature_names, boston.target_names

(['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 ['MEDV'])

In [19]:
type(boston.data)

pandas.core.frame.DataFrame

In [20]:
from sklearn.linear_model import LinearRegression

X = boston.data
y = boston.target

In [21]:
from sklearn.model_selection import KFold

kfold = KFold(5)

kfold.split(X)

In [22]:
list(kfold.split(X))

[(array([102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
         115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
         128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
         141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
         167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
         180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
         193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
         206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
         219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
         232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
         245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257,
         258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
         271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283,
         284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296,
         297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309,
         310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322,
         323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335,
         336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348,
         349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361,
         362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374,
         375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387,
         388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400,
         401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413,
         414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426,
         427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439,
         440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452,
         453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465,
         466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478,
         479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491,
         492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
         505]),
  array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
          39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
          52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
          65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
          78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
          91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101])),
 (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
          39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
          52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
          65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
          78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
          91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 203, 204,
         205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
         218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
         231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243,
         244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256,
         257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269,
         270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282,
         283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295,
         296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308,
         309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321,
         322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334,
         335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347,
         348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360,
         361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373,
         374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386,
         387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399,
         400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
         413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
         426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
         439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
         452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
         465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
         478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490,
         491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503,
         504, 505]),
  array([102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
         115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
         128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
         141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
         167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
         180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
         193, 194, 195, 196, 197, 198, 199, 200, 201, 202])),
 (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
          39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
          52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
          65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
          78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
          91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
         104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
         117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
         130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
         143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
         156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
         169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
         182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
         195, 196, 197, 198, 199, 200, 201, 202, 304, 305, 306, 307, 308,
         309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321,
         322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334,
         335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347,
         348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360,
         361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373,
         374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386,
         387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399,
         400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
         413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
         426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
         439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
         452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
         465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
         478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490,
         491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503,
         504, 505]),
  array([203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
         216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
         229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
         242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
         255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
         268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
         281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293,
         294, 295, 296, 297, 298, 299, 300, 301, 302, 303])),
 (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
          39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
          52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
          65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
          78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
          91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
         104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
         117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
         130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
         143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
         156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
         169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
         182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
         195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
         208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
         221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
         234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
         247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
         260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
         273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
         286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
         299, 300, 301, 302, 303, 405, 406, 407, 408, 409, 410, 411, 412,
         413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
         426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
         439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
         452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
         465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
         478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490,
         491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503,
         504, 505]),
  array([304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
         317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329,
         330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
         343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355,
         356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368,
         369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381,
         382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394,
         395, 396, 397, 398, 399, 400, 401, 402, 403, 404])),
 (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
          26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
          39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
          52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
          65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
          78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
          91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
         104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
         117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
         130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
         143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
         156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
         169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
         182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
         195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
         208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
         221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
         234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
         247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
         260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
         273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
         286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
         299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
         312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
         325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
         338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
         351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
         364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
         377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
         390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
         403, 404]),
  array([405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417,
         418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430,
         431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443,
         444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456,
         457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469,
         470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482,
         483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495,
         496, 497, 498, 499, 500, 501, 502, 503, 504, 505]))]

In [23]:
from sklearn.metrics import r2_score

r2_scores = []
lr = LinearRegression()

In [ ]:
from sklearn.metrics import r2_score

r2_scores = []
lr = LinearRegression()

for train_idx, test_idx in kfold.split(X):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    reg = lr.fit(X_train, y_train)
    y_pred = reg.predict(X_test)

    r2 = r2_score(y_test, y_pred)
    r2_scores.append(r2)

In [ ]:
r2_scores

In [ ]:
for i, r2 in enumerate(r2_scores):
    print(i+1, f'- R2 ={r2:.3f}')

print(f'average R2 = {np.round(np.mean(r2_scores),3)}')

#### 2. cross_val_score()를 활용하여 r2값을 구하시오.(소숫점 이하 세자리)

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

kfold = KFold(5)
lr = LinearRegression()

print(cross_val_score(lr,X,y, cv=5))
print(np.round(np.mean(cross_val_score(lr,X,y, cv=5)),3))